stages:
  - build
  - deploy

# BUILD
.Build template: &build_template
  image: docker:stable
  stage: build
  tags: [au, docker]
  script:
    # Login Docker-registry
    - docker login -u "gitlab-ci-token" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    # Make BUILD_INFO
    - >
      BUILD_INFO="[$(date +'%Y-%m-%d %H:%M:%S %z')] $(docker -v)
        Git[$CI_PROJECT_URL] Reference[$CI_COMMIT_REF_NAME] $CI_COMMIT_SHA
        Pipeline[$CI_PIPELINE_ID] Build[$CI_BUILD_ID] User[$GITLAB_USER_LOGIN]
        Runner[$CI_RUNNER_ID:$CI_RUNNER_DESCRIPTION]"
    - echo $BUILD_INFO
    # Build
    - |
      docker build -f ./Dockerfile \
        --build-arg BUILD_INFO="${BUILD_INFO}" \
        --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} \
        .
    # Push into Docker-registry
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    # Print the job's end time
    - date "+'%Y-%m-%d %H:%M:%S %z'"

Build Beta (auto):
  <<: *build_template
  only:
    - /^[0-9.]{1,8}[.-](beta)[0-9.]{1,3}$/

# DEPLOY
.Deploy template: &deploy_template
  image: dtzar/helm-kubectl:3.4.0
  stage: deploy
  tags: [au, docker]
  script:
    - mkdir ~/.kube
    - echo ${K8S_CONFIG} | base64 -d > ~/.kube/config
    - egrep "current-context|name|server" ~/.kube/config
    - kubectl version
    # Apply Changes
    - kubectl set image deployment/${CI_PROJECT_NAME} --namespace ${NAMESPACE} ${CI_PROJECT_NAME}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  variables:
    K8S_CONFIG: '${KUBE_CONFIG}'

Deploy IEC (auto):
  <<: *deploy_template
  tags: [au, docker, office]
  environment:
    name: 'iec'
  only:
    - /^[0-9.]{1,8}[.-](beta|rc)[0-9.]{1,3}$/
  variables:
    K8S_CONFIG: '${KUBE_CONFIG_IEC}'
    NAMESPACE: 'default'
